package deskcalc;

import java.util.Observable;
import java.util.Observer;

/**
 * [電卓]　電卓のビュー
 *
 * @author masato
 */
public class DeskCalcView extends javax.swing.JPanel implements Observer {

    /**
     * 電卓のモデル
     */
    private DeskCalc model = null;

    /**
     * コンストラクタ
     */
    public DeskCalcView() {
        initComponents();
    }

    /**
     * [コンストラクタ]
     *
     * @param model 電卓のモデル
     */
    public DeskCalcView(DeskCalc model) {
        this();
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        memoryLabel = new javax.swing.JLabel();

        resultTextField.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        resultTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultTextField.setText("0");
        resultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextFieldActionPerformed(evt);
            }
        });

        stateLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        stateLabel.setText("INIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(memoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stateLabel)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(memoryLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTextFieldActionPerformed
    /**
     * [Observer] ビューの更新
     *
     * @param c 監視対象（電卓のモデル）
     * @param arg 更新の引数
     */
    public void update(Observable c, Object arg) {
        resultTextField.setText(Double.toString((model.getResult())));

        stateLabel.setText(model.getStatus().toString());
        if (model.hasMemory()) {
            memoryLabel.setText("[M]");
        } else {
            memoryLabel.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel memoryLabel;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables
}
