//====================================================================
package deskcalc;
//====================================================================
import java.awt.BorderLayout;
import java.util.Observer;
//====================================================================
/**
 *[電卓]　電卓のウィンドウ
 * @author masato
 */
public class DeskCalcFrame extends javax.swing.JFrame {
    //モデル・ビュー・コントロールの三つをここで表示させるために三つの変数
    /**
     * 電卓のモデル
     */
    private DeskCalc model = null;
    /**
     * 電卓のビュー
     */
    private DeskCalcView view = null;
    /**
     * 電卓のコントローラ
     */
    private DeskCalcControl control = null;
    //====================================================================
    //[コンストラクタ]
    /**
     * Creates new form DeskCalcFrame コンストラクタ
     */
    public DeskCalcFrame() {
        initComponents();
        //
        //モデルはビューもコントロールも知らない
        //ビューはモデルを知ってる
        //コントロールはモデルもビューも知ってる
        model =  new DeskCalc();
        view = new DeskCalcView(model);
        control = new DeskCalcControl(model, view);
        //
        model.addObserver((Observer)view);
        //
        
       setLayout( new BorderLayout());
       add( view, BorderLayout.NORTH);
       add( control, BorderLayout.CENTER);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
