
package deskcalc;
//コントロールするためのキーの集まり

/**
 *[電卓]　電卓のコントローラ
 * @author masato
 * @version 1.0 2014.07.04 masato
 */

public class DeskCalcControl extends javax.swing.JPanel {

    private DeskCalc model = null;
    private DeskCalcView view = null;

    /**
     * [コンストラクタ]
     */
    public DeskCalcControl() {
        initComponents();
    }
    /**
     * [コンストラクタ]
     * @param model 電卓のモデル
     * @param view 電卓のビュー
     */
    public DeskCalcControl(DeskCalc model, DeskCalcView view) {
        this();
        //
        this.model = model;
        this.view = view;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n0Button = new javax.swing.JButton();
        n1Button = new javax.swing.JButton();
        n4Button = new javax.swing.JButton();
        n7Button = new javax.swing.JButton();
        n2Button = new javax.swing.JButton();
        n3Button = new javax.swing.JButton();
        n5Button = new javax.swing.JButton();
        n6Button = new javax.swing.JButton();
        n8Button = new javax.swing.JButton();
        n9Button = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        mulButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        rutoButton = new javax.swing.JButton();
        monClearButton = new javax.swing.JButton();
        monRestorButton = new javax.swing.JButton();
        momPlusButton = new javax.swing.JButton();
        momMinusButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();

        n0Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n0Button.setText("0");
        n0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ButtonActionPerformed(evt);
            }
        });

        n1Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n1Button.setText("1");
        n1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ButtonActionPerformed(evt);
            }
        });

        n4Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n4Button.setText("4");
        n4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ButtonActionPerformed(evt);
            }
        });

        n7Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n7Button.setText("7");
        n7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ButtonActionPerformed(evt);
            }
        });

        n2Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n2Button.setText("2");
        n2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ButtonActionPerformed(evt);
            }
        });

        n3Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n3Button.setText("3");
        n3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ButtonActionPerformed(evt);
            }
        });

        n5Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n5Button.setText("5");
        n5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ButtonActionPerformed(evt);
            }
        });

        n6Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n6Button.setText("6");
        n6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ButtonActionPerformed(evt);
            }
        });

        n8Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n8Button.setText("8");
        n8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ButtonActionPerformed(evt);
            }
        });

        n9Button.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        n9Button.setText("9");
        n9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        subButton.setText("-");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        mulButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        mulButton.setText("*");
        mulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulButtonActionPerformed(evt);
            }
        });

        divButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        divButton.setText("÷");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        equalButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        equalButton.setText("＝");
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        clearButton.setText("Ｃ");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        pointButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        pointButton.setText(".");
        pointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointButtonActionPerformed(evt);
            }
        });

        rutoButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        rutoButton.setText("√");
        rutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutoButtonActionPerformed(evt);
            }
        });

        monClearButton.setText("MC");
        monClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monClearButtonActionPerformed(evt);
            }
        });

        monRestorButton.setText("MR");
        monRestorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monRestorButtonActionPerformed(evt);
            }
        });

        momPlusButton.setText("MP");
        momPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                momPlusButtonActionPerformed(evt);
            }
        });

        momMinusButton.setText("MM");
        momMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                momMinusButtonActionPerformed(evt);
            }
        });

        logButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        logButton.setText("Ln");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n1Button)
                                .addGap(18, 18, 18)
                                .addComponent(n2Button)
                                .addGap(18, 18, 18)
                                .addComponent(n3Button))
                            .addComponent(n0Button)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(n4Button)
                                        .addGap(18, 18, 18)
                                        .addComponent(n5Button)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(n7Button)
                                        .addGap(18, 18, 18)
                                        .addComponent(n8Button)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(n9Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(n6Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subButton)
                                    .addComponent(addButton)
                                    .addComponent(mulButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(equalButton)
                                    .addComponent(clearButton)
                                    .addComponent(rutoButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(divButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pointButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monRestorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(momPlusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(momMinusButton)
                        .addGap(4, 4, 4)
                        .addComponent(logButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n7Button)
                    .addComponent(n8Button)
                    .addComponent(n9Button)
                    .addComponent(addButton)
                    .addComponent(equalButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n4Button)
                    .addComponent(n5Button)
                    .addComponent(n6Button)
                    .addComponent(subButton)
                    .addComponent(clearButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n1Button)
                        .addComponent(n2Button)
                        .addComponent(n3Button)
                        .addComponent(mulButton))
                    .addComponent(rutoButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n0Button)
                    .addComponent(divButton)
                    .addComponent(pointButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monClearButton)
                    .addComponent(monRestorButton)
                    .addComponent(momPlusButton)
                    .addComponent(momMinusButton)
                    .addComponent(logButton))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeskCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeskCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeskCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeskCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeskCalcFrame().setVisible(true);
            }
        });
    }
    
    //[イベントハンドラ] 数字キー
    private void n9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ButtonActionPerformed
        model.pushDigitKeyEvent('9');
    }//GEN-LAST:event_n9ButtonActionPerformed

    private void n1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ButtonActionPerformed
        model.pushDigitKeyEvent('1');
    }//GEN-LAST:event_n1ButtonActionPerformed

    private void n6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ButtonActionPerformed
        model.pushDigitKeyEvent('6');
    }//GEN-LAST:event_n6ButtonActionPerformed

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
        model.pushOpKeyEvent(Op.SUB);
    }//GEN-LAST:event_subButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        model.pushClearKeyEvent();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void n0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ButtonActionPerformed
        model.pushDigitKeyEvent('0');
    }//GEN-LAST:event_n0ButtonActionPerformed

    private void n2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ButtonActionPerformed
        model.pushDigitKeyEvent('2');
    }//GEN-LAST:event_n2ButtonActionPerformed

    private void n3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ButtonActionPerformed
        model.pushDigitKeyEvent('3');
    }//GEN-LAST:event_n3ButtonActionPerformed

    private void n4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ButtonActionPerformed
        model.pushDigitKeyEvent('4');
    }//GEN-LAST:event_n4ButtonActionPerformed

    private void n5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ButtonActionPerformed
        model.pushDigitKeyEvent('5');
    }//GEN-LAST:event_n5ButtonActionPerformed

    private void n7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ButtonActionPerformed
        model.pushDigitKeyEvent('7');
    }//GEN-LAST:event_n7ButtonActionPerformed

    private void n8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ButtonActionPerformed
        model.pushDigitKeyEvent('8');
    }//GEN-LAST:event_n8ButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        model.pushOpKeyEvent(Op.ADD);
    }//GEN-LAST:event_addButtonActionPerformed

    private void mulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulButtonActionPerformed
        model.pushOpKeyEvent(Op.MUL);
    }//GEN-LAST:event_mulButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        model.pushOpKeyEvent(Op.DIV);
    }//GEN-LAST:event_divButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
       model.pushOpKeyEvent(Op.EQUAL);
    }//GEN-LAST:event_equalButtonActionPerformed

    private void pointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointButtonActionPerformed
        model.pushPointKeyEvent();
    }//GEN-LAST:event_pointButtonActionPerformed

    private void rutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutoButtonActionPerformed
        model.pushRutoKeyEvent();        // TODO add your handling code here:
    }//GEN-LAST:event_rutoButtonActionPerformed

    private void monClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monClearButtonActionPerformed
        model.pushMemoryClearKeyEvent();
    }//GEN-LAST:event_monClearButtonActionPerformed

    private void momMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_momMinusButtonActionPerformed
       model.pushMemoryMinusKeyEvent();
    }//GEN-LAST:event_momMinusButtonActionPerformed

    private void monRestorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monRestorButtonActionPerformed
        model.pushMemoryRestorKeyEvent();
    }//GEN-LAST:event_monRestorButtonActionPerformed

    private void momPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_momPlusButtonActionPerformed
        model.pushMemoryPlusKeyEvent();
    }//GEN-LAST:event_momPlusButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        model.pushLogKeyEvent();
    }//GEN-LAST:event_logButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton logButton;
    private javax.swing.JButton momMinusButton;
    private javax.swing.JButton momPlusButton;
    private javax.swing.JButton monClearButton;
    private javax.swing.JButton monRestorButton;
    private javax.swing.JButton mulButton;
    private javax.swing.JButton n0Button;
    private javax.swing.JButton n1Button;
    private javax.swing.JButton n2Button;
    private javax.swing.JButton n3Button;
    private javax.swing.JButton n4Button;
    private javax.swing.JButton n5Button;
    private javax.swing.JButton n6Button;
    private javax.swing.JButton n7Button;
    private javax.swing.JButton n8Button;
    private javax.swing.JButton n9Button;
    private javax.swing.JButton pointButton;
    private javax.swing.JButton rutoButton;
    private javax.swing.JButton subButton;
    // End of variables declaration//GEN-END:variables
}
